[project]
name = "evm-raw-contract-calls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ecdsa>=0.19.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]